# This is for github project pages
# japhethcrawford.github.io/advancedweb
# japhethcrawford.github.io
baseurl: /advancedweb
markdown: redcarpet

name: mywebsite
Description: My Jekyll Website

author: 
	name: Japheth Crawford	
	email: japhethcrawford@gmail.com
	github: japhethcrawford
	twitter: @japhethcrawford
	
permalink: pretty

future: true

##(default) show_drafts: false 

